version: '2'
services:
  web:
    images: tomcat-maven:latest
    links:
      - maven
    ports:
      - "8080:8080"
    volumes:
      - data_volume:/usr/local/tomcat/webapps
  maven:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - data_volume:/boxfuse-sample-java-war-hello/target/

